# Generated by Django 4.1.5 on 2023-01-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(help_text='Längere Beschreibung des Items', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(help_text='Name des Items', max_length=200, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='position',
            field=models.CharField(help_text='Position im Lager', max_length=200, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='producer',
            field=models.CharField(help_text='Hersteller des Items', max_length=200, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(help_text='Anzahl', verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ended_at',
            field=models.DateTimeField(help_text='Ende der Ausleihe', null=True, verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(help_text='Item', on_delete=django.db.models.deletion.CASCADE, to='app.inventoryitem', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(help_text='Anzahl', verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='order',
            name='started_at',
            field=models.DateTimeField(help_text='Beginn der Ausleihe', null=True, verbose_name='Beginn'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(help_text='status', max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Benutzer', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email-Adresse des Benutzers', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Name des Benutzers', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Passwort', max_length=200, verbose_name='Passwort'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Telefonnummer', max_length=200, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sur_name',
            field=models.CharField(help_text='Nachname des Benutzers', max_length=200, verbose_name='Nachname'),
        ),
    ]
