# Generated by Django 4.1.5 on 2023-01-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='images/')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventoryitem')),
            ],
        ),
    ]
