# Generated by Django 4.1.5 on 2023-01-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inventoryitemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemimage',
            name='inventory_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.inventoryitem'),
        ),
    ]
