# Generated by Django 4.1.5 on 2023-01-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('ARCHIVED', 'archived'), ('RESERVED', 'reserved')], default='ACTIVE', help_text='status', max_length=200, verbose_name='Status'),
        ),
    ]
