# Generated by Django 4.1.5 on 2023-01-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_inventoryitemimage_inventory_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='returned',
            field=models.BooleanField(default=False, help_text='Item wurde zurückgegeben', verbose_name='Zurückgegeben'),
        ),
        migrations.AlterField(
            model_name='inventoryitemimage',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
