# Generated by Django 4.1.5 on 2023-01-30 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_order_state_order_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='active',
            field=models.BooleanField(default=True, editable=False, help_text='Item ist active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(help_text='Detailed desscription of the Item', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(help_text='Name of the Item', max_length=200, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='position',
            field=models.CharField(help_text='Position in the basement', max_length=200, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='producer',
            field=models.CharField(help_text='Producer of them Items', max_length=200, verbose_name='Producer'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(help_text='Quantity', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ended_at',
            field=models.DateTimeField(help_text='End of the Order', null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(help_text='Quantity', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='returned',
            field=models.BooleanField(default=False, help_text='Item was returned', verbose_name='Returned'),
        ),
        migrations.AlterField(
            model_name='order',
            name='started_at',
            field=models.DateTimeField(help_text='Start of the Order', null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
