# Generated by Django 4.1.5 on 2023-01-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_state_order_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemimage',
            name='inventory_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.inventoryitem'),
        ),
    ]
