# Generated by Django 4.1.5 on 2023-01-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_inventoryitem_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
    ]
