# Generated by Django 4.1.5 on 2023-01-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_document_alter_inventoryitem_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Category', max_length=200, verbose_name='Category Name')),
                ('description', models.TextField(help_text='Detailed description of the Category', null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, editable=False, help_text='Category ist active', verbose_name='Active')),
                ('color', models.CharField(help_text='Color of the Category', max_length=200, null=True, verbose_name='Color')),
                ('icon', models.CharField(help_text='Icon of the Category', max_length=200, null=True, verbose_name='Icon')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(default=None, help_text='Category of the Item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category', verbose_name='Category'),
        ),
    ]
