# Generated by Django 4.1.5 on 2023-01-31 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_inventoryitem_active_and_more'),
        ('app', '0007_category_inventoryitem_category'),
    ]

    operations = [
    ]
