# Generated by Django 4.1.5 on 2023-01-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20230130_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='priceperunit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per Unit', max_digits=5, null=True, verbose_name='Price per Unit'),
        ),
    ]
