# Generated by Django 4.1.5 on 2023-01-25 13:43
import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_order_state_order_returned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default=app.models._createHash, help_text='Hash of the Item', max_length=48, unique=True, verbose_name='Hash')),
                ('serial_number', models.CharField(help_text='Serial Number of the Item', max_length=200, verbose_name='Serial Number')),
                ('active', models.BooleanField(default=True, help_text='Item ist active', verbose_name='Active')),
                ('inventory_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.inventoryitem')),
            ],
        ),

    ]
