# Generated by Django 4.1.5 on 2023-01-30 10:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_remove_inventoryitem_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Lend',
        ),
    ]
