# Generated by Django 4.1.5 on 2023-01-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_order_lend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lend',
            name='item',
        ),
        migrations.AddField(
            model_name='lend',
            name='single_item',
            field=models.ManyToManyField(help_text='Item', to='app.singleinventoryitem', verbose_name='Item'),
        ),
    ]
