# Generated by Django 4.1.5 on 2023-01-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_lend_item_lend_single_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lend',
            name='quantity',
        ),
    ]
