# Generated by Django 4.1.5 on 2023-02-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_inventoryitem_priceperunit'),
        ('app', '0014_remove_lend_quantity'),
    ]

    operations = [
    ]
